### ISSUE TITLE
view moves up constantly

### ISSUE THREAD

**Issue by Paktosan** [gamax92/wine-overwatch#11]
OS: openSUSE Leap 42.2
Wine version: 2.9
Overwatch version: 1.11.1.2.36923
Game works fine so far however the view is constantly moving up.

**Comment by zekesonxx** [comment]
Do you have a game controller plugged in that's being detected by Wine? That's the usual cause of issues like this.

Run `wine control` in the prefix and see if it's detecting any game controllers.

**Comment by imbavirus** [comment]
Make sure your aspect ratio and resolution are set correctly to match your screen

**Comment by Paktosan** [comment]
Wine does not show any controllers which  makes sense since none are plugged in. My display is a Dell P2213 1680x1050 16:10 monitor. I now noticed that Overwatch was set to 16:9. I fixed that. Did not know that this was possible since I remember not having that option under Windows.

**Comment by IRedFoxI** [comment]
My screen is a 4:3 ratio, which I can't select in the game. So my view is scrolling up all the time, making the game unplayable under linux.

**Comment by zekesonxx** [comment]
Overwatch doesn't support 4:3 aspect ratios, even on Windows. This is
outside the scope of wine-overwatch.

On Jul 3, 2017 4:18 PM, "IRedFoxI" <notifications@github.com> wrote:

My screen is a 4:3 ratio, which I can't select in the game. So my view is
scrolling up all the time, making the game unplayable under linux.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/gamax92/wine-overwatch/issues/11#issuecomment-312726678>,
or mute the thread

**Comment by IRedFoxI** [comment]
I don't know what you meant by writing it doesn't support it, but I can say that it _is_ playable under windows.

**Comment by gamax92** [comment]
We don't know *why* the view moves when the actual resolution and aspect ratio setting don't match, but we do know making sure they match avoids the issue.

As @zekesonxx stated, there is no 4:3 option available in the Overwatch settings so you will have to choose a different resolution if possible.

**Comment by zekesonxx** [comment]
@IRedFoxI If you were playing letterboxed on Windows, you might try playing in a window on Linux.
