### ISSUE TITLE
Random frame drops

### ISSUE THREAD

**Issue by Riokei** [gamax92/wine-overwatch#12]
Was testing with the new lutris installer for this (which is using 2.9) and noticed random frame drops in the tutorial, otherwise it stayed at 60FPS is this a settings issue or a wine issue?

**Comment by gamax92** [comment]
It's just a wine issue, unless you have a super beefy fast computer don't expect this to run fast right now.

**Comment by zekesonxx** [comment]
Wine's D3D11 is largely unoptimized and heavily CPU bound; this in comparison to Wine D3D9, which is basically feature complete and optimized to the point of running some older games *better* than Windows can.

@Riokei some general performance recommendations:
* CSMT on
* All graphics settings on lowest and work up from there
  * Textures higher than `Low` will randomly be black instead of the needed texture. This happens in some other games too.
* Turning off voice chat (just switching it to no-autojoin works) prevents some of the stuttering when joining matches
* Reduce CPU usage from other things as much as possible.

Overwatch is already very heavily optimized on Windows (nearly to the point of League), so there isn't really anything like hidden superlow config settings you might find in other games.On the other hand, Overwatch's optimizations are also probably the only reason it's at playable performance on decent hardware, instead of the 5-10 FPS fest that most D3D11 games are right now.
