### ISSUE TITLE
No compatible graphics hardware found.

### ISSUE THREAD

**Issue by fundies** [gamax92/wine-overwatch#7]
http://i.imgur.com/4xeim38.png

4.10.13-1-ARCH
04:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480] (rev c7)

extra/xf86-video-amdgpu 1.3.0-1 (xorg-drivers) [installed]
extra/xorg-server 1.19.3-2 (xorg) [installed]

**Comment by imbavirus** [comment]
Overwatch does not work with the opensource mesa drivers, you need to install the amdgpu-pro driver to fix this issue

**Comment by fundies** [comment]
unfortunately that really isn't possible on current archlinux :(

**Comment by imbavirus** [comment]
I am running amdgpu-pro on the current latest version of arch, you simply add the xorg118 repo to your pacman.conf, underneath [core] and then you run pacman -Syuu to get xorg118, also you dont need libglvnd since amdgpu-pro provides libgl and all those libraries.  There were some additional things I had to install and file conflicts I had to overcome, however it does most certainly work, even on GCN1.0 cards. However it is the only way you'll get overwatch running with your card on linux for now, since mesa does not have the compatibilty profiles to support directx 11 conversion yet.

**Comment by renyuneyun** [comment]
Same issue with Intel HD 5500.

**Comment by imbavirus** [comment]
Yes, since intel does not have any proprietary driver and only uses the mesa opensource drivers, it also does not have the compatibility profiles to support directX 11, you can always run:
>export MESA_GL_VERSION_OVERRIDE=4.3COMPAT
>export MESA_GLSL_VERSION_OVERRIDE=43

before starting overwatch, and it will open, but you'll be greeted by a black screen due to the missing compatibility profiles

**Comment by fundies** [comment]
I managed to get amdgpu-pro installed but now I get configure: WARNING: No OpenGL library found on this system. when trying to build :/

[greg@greg-desktop wine-overwatch]$ glxinfo | grep version
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL core profile version string: 4.5.13474 Core Profile Context 17.10.2
OpenGL core profile shading language version string: 4.50
OpenGL version string: 4.5.13474 Compatibility Profile Context 17.10.2
OpenGL shading language version string: 4.50
OpenGL ES profile version string: 4.5.13474 Compatibility Profile Context 17.10.2
OpenGL ES profile shading language version string: 4.50

**Comment by imbavirus** [comment]
@fundies  this should fix that for you:

>cd /usr/lib/
>sudo ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libGL.so libGL.so
>sudo ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libGL.so.1 libGL.so.1
>sudo ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libGL.so.1.2 libGL.so.1.2
>sudo ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libEGL.so libEGL.so
>sudo ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libEGL.so.1 libEGL.so.1
>sudo ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libGLESv2.so libGLESv2.so
>sudo ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libGLESv2.so.2 libGLESv2.so.2
>
>cd /usr/lib32/
>sudo ln -s /opt/amdgpu-pro/lib/i386-linux-gnu/libGL.so libGL.so
>sudo ln -s /opt/amdgpu-pro/lib/i386-linux-gnu/libGL.so.1 libGL.so.1
>sudo ln -s /opt/amdgpu-pro/lib/i386-linux-gnu/libGL.so.1.2 libGL.so.1.2
>sudo ln -s /opt/amdgpu-pro/lib/i386-linux-gnu/libEGL.so libEGL.so
>sudo ln -s /opt/amdgpu-pro/lib/i386-linux-gnu/libEGL.so.1 libEGL.so.1
>sudo ln -s /opt/amdgpu-pro/lib/i386-linux-gnu/libGLESv2.so libGLESv2.so
>sudo ln -s /opt/amdgpu-pro/lib/i386-linux-gnu/libGLESv2.so.2 libGLESv2.so.2

**Comment by fundies** [comment]
now it says I need 64bit OS to install overwatch...

**Comment by imbavirus** [comment]
Make sure you compiled wine for 64 bit and that you are using a 64 bit prefix.
Refer to: https://github.com/gamax92/wine-overwatch/issues/5

**Comment by fundies** [comment]
well I got it running but its damn slow. 30fps max if nothing is going on (im on on low 720p window with 50% render size) Also my gold guns are invisible XD

**Comment by imbavirus** [comment]
Yea performance is still quite a mystery for some, where some systems run it great at 60fps (also on low though) and some people barely manage like 12fps, if that much.... however you might want to look at https://lutris.net/games/overwatch/ and see if there are any additional settings/registry keys that Djazz applied that might help you improve the performance
